### ISSUE TITLE
Remove dependency on ActiveSupport

### ISSUE THREAD

**Issue by reagent** [reagent/fleakr#9]
This is only used in a few places - it would be better to get rid of it rather than supporting multiple versions (2.x, 3.x).

**Comment by konklone** [comment]
Yeah, it's tough to use this in my Rails 3 project, for its incompatibility with ActiveSupport 3.x.

I changed fleakr.rb's active support include section to be this, and it worked with Rails 3:

require 'active_support/core_ext/array'
require 'active_support/core_ext/module'

require 'active_support/core_ext/object/blank'

require 'active_support/core_ext/time/acts_like'
require 'active_support/core_ext/time/calculations'
require 'active_support/core_ext/time/conversions'
require 'active_support/core_ext/time/marshal'
require 'active_support/core_ext/time/publicize_conversion_methods'
require 'active_support/core_ext/time/zones'
require 'active_support/lazy_load_hooks'
require 'active_support/inflector'
require 'active_support/core_ext/string'

I didn't know which time methods you were using, so I included each time class. Also important is the include of lazy_load_hooks.

**Comment by reagent** [comment]
This commit removes the dependency on AS:

https://github.com/reagent/fleakr/commit/c498243cc9f54db33bfc1acf62deb7c4fa58b9fb

I will be tidying up the documentation and will release 0.7.0 in the next day or so.

**Comment by konklone** [comment]
Awesome! Thanks, looking forward to it.
